### ISSUE TITLE
Site Confirmation E-mails [Not being received]

### ISSUE THREAD

**Issue by Kauldwin** [RoyalRaid/VenomPvP#8] opened 2017-01-01 13:56 UTC
People aren't getting their verified emails within the day of registering it can take upto 3 days to come through. Had 3 players complain about this, This is stopping users signing up to the forums

**Comment by RoyalRaid** [comment] 2017-01-01 23:55
Have they checked their spam/junk folder?

**Comment by RoyalRaid** [comment] 2017-01-03 09:23
Closing this issue! as most of the cases that people couldnt confirm their account was because they already had a account with the same email or it was in the junk folder!

**Comment by Zaid-Ali** [comment] 2017-01-04 16:12
Issue still exists: http://prnt.sc/drg0ku

Checked both his mail and he confirmed he did not have an account with the same email.

**Comment by Zaid-Ali** [comment] 2017-01-06 20:31
http://venompvp.org/members/jason.983/ Same issue.

**Comment by Zaid-Ali** [comment] 2017-01-06 22:16
http://www.venompvp.org/members/steveisallama.996/ Same issue.

**Comment by Zaid-Ali** [comment] 2017-01-07 19:19
http://venompvp.org/members/insusceptibility.1022/ Same issue.

**Comment by RoyalRaid** [comment] 2017-01-09 11:12
hm, Im gonna investigate further with this, Might have to setup some new email settings.

**Comment by Blackouma** [comment] 2017-01-16 17:37
When two of my friends were screwing around and trying to make troll apps it took them a while to get the emails, they checked the spam folders and I was sitting right next to them as they signed up and such so I know they didn't enter anything wrong. I'm not sure if they ever even ended up getting the emails.

**Comment by RoyalRaid** [comment] 2017-01-17 09:18
did they use the same email to register?

**Comment by Zaid-Ali** [comment] 2017-01-17 19:56
http://venompvp.org/members/molten23.1056/ Same issue.

**Comment by Zaid-Ali** [comment] 2017-01-30 13:44
Resolved.

**Closed by Zaid-Ali** 2017-01-30 13:44 UTC
Labels: bug, help wanted
